import openai
import json
from typing import List
from openai import OpenAI
from dotenv import load_dotenv
import os
import inspect
import random
import re
from langchain.tools import tool
from langchain.agents import create_agent 
from langchain_openai import ChatOpenAI

load_dotenv()

openai.api_key = os.getenv("OPENAI_API_KEY")

model = ChatOpenAI(
    model="gpt-4o-mini",
    api_key=os.getenv("OPENAI_API_KEY")
)

def extract_response(response):
    """Extract text from various LangChain response formats."""
    # Handle dict with 'output' key
    if isinstance(response, dict) and 'output' in response:
        return response['output']
    # Handle dict with 'text' key
    if isinstance(response, dict) and 'text' in response:
        return response['text']
    # Handle AIMessage or similar objects with content attribute
    if hasattr(response, 'content'):
        return response.content
    # Handle string directly
    if isinstance(response, str):
        return response
    # Handle dict, try to find any text-like value
    if isinstance(response, dict):
        # Try 'messages' key for agent responses
        if 'messages' in response and isinstance(response['messages'], list) and response['messages']:
            last_msg = response['messages'][-1]
            if hasattr(last_msg, 'content'):
                return last_msg.content
            if isinstance(last_msg, dict) and 'content' in last_msg:
                return last_msg['content']
    # Fallback to string representation
    return str(response)

### Puzzle generation and validation tools ###

@tool
def generate_riddle() -> str:
    """Returns a riddle puzzle (question + correct answer) generated by LLM."""
    prompt = "Generate a single riddle puzzle for an escape room. Format: RIDDLE: [riddle question] ANSWER: [short answer]"
    return model.invoke(prompt).content

@tool
def generate_math_puzzle() -> str:
    """Returns a math puzzle (question + correct answer) generated by LLM."""
    prompt = "Generate a single math puzzle for an escape room. Format: PUZZLE: [math question] ANSWER: [numerical answer]"
    return model.invoke(prompt).content

@tool
def generate_word_puzzle() -> str:
    """Returns a word puzzle (question + correct answer) generated by LLM."""
    prompt = "Generate a single word puzzle for an escape room. Format: PUZZLE: [word puzzle question] ANSWER: [short word answer]"
    return model.invoke(prompt).content

# Store the underlying functions for calling from random_puzzle
_generate_riddle = generate_riddle.func
_generate_math_puzzle = generate_math_puzzle.func
_generate_word_puzzle = generate_word_puzzle.func

@tool
def random_puzzle(type=None):
    """Picks a puzzle type at random (or based on type) and generates via LLM."""
    if type == "riddle":
        return _generate_riddle()
    elif type == "math":
        return _generate_math_puzzle()
    elif type == "word":
        return _generate_word_puzzle()
    else:
        puzzle_func = random.choice([_generate_riddle, _generate_math_puzzle, _generate_word_puzzle])
        return puzzle_func()

@tool
def parse_puzzle_response(response):
    """Uses LLM to intelligently extract question and answer from puzzle response."""
    prompt = f"""You are a puzzle extractor. Given a puzzle text that contains both a question and an answer, 
extract them separately and return ONLY this format (nothing else):
QUESTION: [the puzzle question without the answer]
ANSWER: [the correct answer - just the answer value, nothing else]

Puzzle to extract from:
{response}"""
    
    result = model.invoke(prompt).content
    
    # Parse the LLM's extraction
    
    question_match = re.search(r'QUESTION:\s*(.+?)(?=ANSWER:|$)', result, re.IGNORECASE | re.DOTALL)
    answer_match = re.search(r'ANSWER:\s*(.+?)$', result, re.IGNORECASE | re.DOTALL)
    
    question = question_match.group(1).strip() if question_match else response.strip()
    answer = answer_match.group(1).strip() if answer_match else ""
    
    return {"question": question, "answer": answer}

@tool
def validate_puzzle_with_llm(puzzle_question: str, puzzle_answer: str) -> dict:
    """
    Use LLM to validate that the answer actually solves the puzzle.
    Returns: {"valid": True/False, "reason": "explanation"}
    """
    prompt = f"""You are a puzzle validator. Check if the provided answer actually solves the puzzle.

PUZZLE QUESTION:
{puzzle_question}

PROVIDED ANSWER:
{puzzle_answer}

Analyze carefully:
1. Read the puzzle question thoroughly
2. Solve it yourself step-by-step
3. Check if there are multiple possible answers
4. Verify the provided answer is correct and unambiguous
5. If multiple answers are possible, the puzzle is INVALID (ambiguous)

Respond with ONLY this JSON format:
{{
    "valid": true or false,
    "reason": "brief explanation",
    "correct_answer": "the correct answer if provided one is wrong, otherwise null",
    "ambiguous": true or false,
    "alternative_answers": ["list", "of", "other", "possible", "answers"] or null
}}

CRITICAL: If a puzzle has multiple valid answers (like "joke" vs "laughter" vs "riddle"), mark it as INVALID with ambiguous=true."""

    try:
        client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"}
        )
        result = json.loads(response.choices[0].message.content)
        
        # If ambiguous, mark as invalid
        if result.get("ambiguous", False):
            result["valid"] = False
            if not result.get("reason"):
                result["reason"] = "Puzzle has multiple possible answers (ambiguous)"
        
        return result
    except Exception as e:
        return {
            "valid": False,
            "reason": f"Validation error: {e}",
            "correct_answer": None,
            "ambiguous": False
        }

### Game State Manager functions ###
game_state = {
    "solved_puzzles": [],
    "unsolved_puzzles": [],
    "attempts": {}
}

@tool
def check_player_answer(puzzle_question: str, correct_answer, player_answer) -> str:
    """Uses LLM to intelligently check if player's answer is correct, considering synonyms and variations."""
    prompt = f"""You are validating a player's answer to a puzzle.

PUZZLE QUESTION:
{puzzle_question}

CORRECT ANSWER:
{correct_answer}

PLAYER'S ANSWER:
{player_answer}

Determine if the player's answer is correct. Consider:
1. Exact matches (case-insensitive)
2. Synonyms or semantically equivalent answers
3. Minor spelling variations or typos
4. Alternative phrasings of the same answer

Examples:
- Correct: "keyboard" vs "key board" → CORRECT
- Correct: "echo" vs "an echo" → CORRECT  
- Correct: "4" vs "four" → CORRECT
- Incorrect: "joke" vs "laughter" → INCORRECT (different words)

Respond with ONLY "True" if correct or "False" if incorrect. No explanation and no additional text.
"""

    result = model.invoke(prompt)
    return result.content

### Hint Master Agent tools ###

# Global hint state tracking
hint_state = {
    "current_puzzle_id": None,
    "hints_given_count": 0
}

@tool
def get_hint(puzzle_question: str, puzzle_answer: str, attempt_count: str) -> str:
    """Provides a hint based on the puzzle question, answer, and number of attempts via LLM."""
    # Increment the hint counter in global state
    hint_state["hints_given_count"] += 1
    attempt_level = hint_state["hints_given_count"]
    
    # Cap at 5 levels
    attempt_level = min(attempt_level, 5)
    
    hint_instructions = {
        1: "Give a very subtle hint that guides toward the solution type. Reference something specific about the puzzle question.",
        2: "Give a hint that points toward a specific aspect of the puzzle. Use elements from the puzzle question to guide them.",
        3: "Give a more direct hint. Reference the puzzle question and guide significantly toward the answer type.",
        4: "Give a very direct hint. You can mention what category the answer falls into or give a strong clue about the answer.",
        5: "Give a hint that's almost the answer. You can reveal part of the answer or describe it very explicitly."
    }
    
    prompt = f"""You are a hint master for escape room puzzles.

PUZZLE QUESTION: {puzzle_question}
CORRECT ANSWER: {puzzle_answer}
HINT LEVEL: {attempt_level}

{hint_instructions[attempt_level]}

CRITICAL RULES:
1. Use the ACTUAL puzzle question and answer above to create your hint
2. Reference specific words or concepts from the puzzle question
3. Do NOT give generic hints like "think carefully" or "look for patterns"
4. Your hint must guide toward the specific answer: {puzzle_answer}
5. Keep it to 1-2 sentences maximum

Provide ONLY the hint text, nothing else:"""
    
    return model.invoke(prompt).content

@tool
def reset_hints(puzzle_id: str = "new_puzzle"):
    """Resets hint progression for a new puzzle."""
    hint_state["current_puzzle_id"] = puzzle_id
    hint_state["hints_given_count"] = 0
    return f"Hints have been reset for puzzle: {puzzle_id}"

### Narrator Agent tools ###
@tool
def intro_story():
    """Sets the opening scene via LLM narrative."""
    prompt = f"""You are a narrator for an escape room adventure.

        First, greet the player and explain the game:
        - They need to solve {num_puzzles} puzzles to escape the ancient temple
        - They can type 'hint' to get up to 3 hints per puzzle
        - They have 5 attempts per puzzle

        Then, create an immersive opening scene (2-3 sentences) that sets the mood for the ancient temple escape room.

        Be dramatic and engaging!"""
    return model.invoke(prompt).content

@tool
def narrate_success(puzzle):
    """Narrates success after solving a puzzle via LLM."""
    prompt = f"Narrate in 1-2 sentences how the player successfully solved this puzzle: {puzzle}. Use dramatic, celebratory language."
    return model.invoke(prompt).content

@tool
def narrate_failure(puzzle):
    """Adds drama when the player fails to solve a puzzle via LLM."""
    prompt = f"Write 1-2 sentences of dramatic narration about the player failing to solve this puzzle: {puzzle}. The temple is trapping them."
    return model.invoke(prompt).content

@tool
def ending(success=True):
    """Concludes the story based on success or failure via LLM."""
    if success:
        prompt = "Write a triumphant 2-3 sentence ending to an escape room story where the player successfully escaped the ancient temple."
    else:
        prompt = "Write a tragic 2-3 sentence ending to an escape room story where the player failed to escape the ancient temple."
    return model.invoke(prompt).content
    

### Instantiate Agents ###

puzzle_generator_agent = create_agent(
    model=model,
    system_prompt="You generate escape room puzzles (riddles, math puzzles, word puzzles) with clear questions and answers.",
    tools=[
            generate_riddle,
            generate_math_puzzle,
            generate_word_puzzle,
            random_puzzle
])

game_state_manager_agent = create_agent(
    model=model,
    system_prompt="You validate player answers and determine if they are correct, considering synonyms and variations.",
    tools=[
            check_player_answer
])

hint_master_agent = create_agent(
    model=model,
    system_prompt="You provide specific, helpful hints for escape room puzzles based on the question and answer. " \
    "Always reference the actual puzzle content in your hints." \
    " Keep track of how many hints have been given and escalate the hints accordingly." \
    " Reset hint progression when a new puzzle starts.",
    tools=[
            get_hint,
            reset_hints
])

narrator_agent = create_agent(
    model=model,
    system_prompt="You are responsible for immersing the player in the escape room story and reacting to progress." \
    "Narrate introductions, successes, failures, and endings with dramatic flair.",
    tools=[
            intro_story,
            narrate_success,
            narrate_failure,
            ending
])


### Convert all agents to tools in order to call them from the orchestrator ###
@tool
def call_puzzle_generator(task: str) -> str:
    """Generates escape room puzzles. Use this to create new riddles, math puzzles, or word puzzles."""
    response = puzzle_generator_agent.invoke({"input": task})
    return extract_response(response)

@tool
def call_game_state_manager(task: str) -> str:
    """Validates player answers. Use this to check if a player's answer is correct."""
    response = game_state_manager_agent.invoke({"input": task})
    return extract_response(response)

@tool
def call_hint_master(task: str) -> str:
    """Provides hints for puzzles. Use this when players need help."""
    response = hint_master_agent.invoke({"input": task})
    return extract_response(response)

@tool
def call_narrator(task: str) -> str:
    """Narrates the story. Use this for introductions, celebrations, failures, and endings."""
    response = narrator_agent.invoke({"input": task})
    return extract_response(response)

# Now create orchestrator with these tools
orchestrator_agent = create_agent(
    model=model,
    system_prompt="""You orchestrate an escape room game.
    You use the following tools to generate puzzles, validate answers, provide hints, and narrate the story.
    Your goal is to create an engaging experience for the player as they attempt to escape by solving puzzles.
    Always decide the best next action based on the game state and player input.
    1. Use the narrator to set the scene and react to player progress.
    2. Use the puzzle generator to create new puzzles.
    3. Use the game state manager to validate player answers.
    4. Use the hint master to provide hints when requested. Inform the player about hint availability and how to ask for a hint.
    Keep track of the number of puzzles solved and remaining.
    Don't give many options to the player at once; guide them step-by-step through the game.
    First, start by introducing the game using the narrator tool.
    Then, generate only the first puzzle using the puzzle generator tool.
    Wait for player input before proceeding further.
    Check player's answers using the game state manager tool.
    If the player requests a hint, use the hint master tool to provide one.
    If the player solves a puzzle, celebrate using the narrator tool and generate the next puzzle.
    If the player fails to solve a puzzle and has more attempts, tell them to try again or ask for a hint.
    If the player fails to solve a puzzle and has no attempts left, narrate the failure and end the game.
    """,
    tools=[
        call_puzzle_generator,
        call_game_state_manager,
        call_hint_master,
        call_narrator
    ]
)


class OrchestratorState:
    def __init__(self, total_puzzles=3):
        self.chat_history = []
        self.game_state = {
            "current_puzzle": 1,
            "total_puzzles": total_puzzles,
            "puzzles_solved": 0,
            "current_attempts": 0,
            "max_attempts": 5,
            "hints_used": 0,
            "max_hints": 3,
            "current_puzzle_question": "",
            "current_puzzle_answer": "",  # ← Store answer here!
        }
    
    def invoke_orchestrator(self, user_message: str):
        """Invoke orchestrator with memory."""
        
        # Build context with current puzzle answer
        context = f"""[GAME STATE]
Puzzle: {self.game_state['current_puzzle']}/{self.game_state['total_puzzles']}
Attempts: {self.game_state['current_attempts']}/{self.game_state['max_attempts']}
Hints: {self.game_state['hints_used']}/{self.game_state['max_hints']}
Puzzles solved: {self.game_state['puzzles_solved']}

CURRENT PUZZLE QUESTION: {self.game_state['current_puzzle_question']}
CORRECT ANSWER: {self.game_state['current_puzzle_answer']}

[USER MESSAGE]
{user_message}"""
        
        response = orchestrator_agent.invoke({
            "input": context,
            "chat_history": self.chat_history
        })
        
        self.chat_history.append(("user", user_message))
        self.chat_history.append(("assistant", extract_response(response)))
        
        return extract_response(response)
    
    def generate_new_puzzle(self):
        """Generate puzzle and store the answer."""
        # Call puzzle generator directly (not through orchestrator)
        puzzle_response = call_puzzle_generator.invoke("Generate a random puzzle")
        
        # Parse to extract question and answer
        parsed = parse_puzzle_response.invoke(puzzle_response)
        
        # Store in state
        self.game_state["current_puzzle_question"] = parsed["question"]
        self.game_state["current_puzzle_answer"] = parsed["answer"].lower().strip()
        
        return parsed["question"]


# Main game loop
def play_game(num_puzzles=3):
    state = OrchestratorState(total_puzzles=num_puzzles)
    
    print("\n" + "="*70)
    print("AI-POWERED ESCAPE ROOM")
    print("="*70 + "\n")
    
    # Get introduction from narrator
    intro = state.invoke_orchestrator(
        f"Use call_narrator to introduce the game. Tell player they need to solve {num_puzzles} puzzles, can use 'hint' for hints (max 3 per puzzle), and have {state.game_state['max_attempts']} attempts per puzzle."
    )
    print(intro)
    
    input("\nPress Enter to continue...")
    
    # Main game loop
    while state.game_state["puzzles_solved"] < num_puzzles:
        print(f"\n{'='*70}")
        print(f"PUZZLE {state.game_state['current_puzzle']} of {num_puzzles}")
        print(f"{'='*70}\n")
        
        # Generate new puzzle and store answer
        puzzle_question = state.generate_new_puzzle()
        print(f"❓ {puzzle_question}\n")
        
        # Reset attempts for new puzzle
        state.game_state["current_attempts"] = 0
        state.game_state["hints_used"] = 0
        puzzle_solved = False
        
        # Puzzle attempt loop
        while state.game_state["current_attempts"] < state.game_state["max_attempts"] and not puzzle_solved:
            user_input = input(f"🔓 Your answer (Attempt {state.game_state['current_attempts'] + 1}/{state.game_state['max_attempts']}): ").strip()
            
            if user_input.lower() == "quit":
                print("Thanks for playing!")
                return
            
            # Handle hint request
            if user_input.lower() == "hint":
                if state.game_state["hints_used"] < state.game_state["max_hints"]:
                    state.game_state["hints_used"] += 1
                    
                    # Ask orchestrator to provide hint
                    response = state.invoke_orchestrator(
                        f"The player requested a hint (hint {state.game_state['hints_used']} of {state.game_state['max_hints']}). Use call_hint_master to provide a hint for the current puzzle."
                    )
                    print(f"\n💡 {response}\n")
                else:
                    print("❌ No more hints available!\n")
                continue
            
            # Increment attempts
            state.game_state["current_attempts"] += 1
            
            # Validate answer through orchestrator
            response = state.invoke_orchestrator(
                f"The player answered: '{user_input}'. Use call_game_state_manager to check if this answer is correct. The correct answer is: {state.game_state['current_puzzle_answer']}"
            )
            
            print(f"\n{response}\n")
            
            # Check if correct
            if "correct" in response.lower() or "right" in response.lower():
                puzzle_solved = True
                state.game_state["puzzles_solved"] += 1
                
                # Celebrate
                celebration = state.invoke_orchestrator(
                    "The player solved the puzzle! Use call_narrator to celebrate their success."
                )
                print(f"{celebration}\n")
                
                state.game_state["current_puzzle"] += 1
                break
            
            elif state.game_state["current_attempts"] >= state.game_state["max_attempts"]:
                # Game over
                failure = state.invoke_orchestrator(
                    f"The player failed after {state.game_state['max_attempts']} attempts. The correct answer was '{state.game_state['current_puzzle_answer']}'. Use call_narrator to dramatize their failure and end the game."
                )
                print(f"{failure}\n")
                return
            else:
                remaining = state.game_state["max_attempts"] - state.game_state["current_attempts"]
                print(f"❌ Incorrect. {remaining} attempts remaining.\n")
        
        if state.game_state["puzzles_solved"] < num_puzzles and puzzle_solved:
            input("\nPress Enter for the next puzzle...")
    
    # Victory!
    victory = state.invoke_orchestrator(
        "The player escaped! Use call_narrator to write a triumphant ending."
    )
    print(f"\n{victory}\n")
    
    print("="*70)
    print("🎉 CONGRATULATIONS! YOU ESCAPED! 🎉")
    print("="*70 + "\n")


if __name__ == "__main__":
    num = input("Number of puzzles (default 3): ")
    num_puzzles = int(num) if num.isdigit() else 3
    play_game(num_puzzles)