import openai
import json
from typing import List
from openai import OpenAI
from dotenv import load_dotenv
import os
import inspect
import random
import re

load_dotenv()

openai.api_key = os.getenv("OPENAI_API_KEY")

class GPTModel:
    def __init__(self, model_name, api_key):
        self.client = OpenAI(api_key=api_key)
        self.model_name = model_name

    def run(self, prompt):
        response = self.client.chat.completions.create(
            model=self.model_name,
            messages=[{"role": "user", "content": prompt}]
        )
        return response.choices[0].message.content
    
gpt = GPTModel(model_name="gpt-4o-mini", api_key=os.getenv("OPENAI_API_KEY"))

class Puzzle_Agent:
    def __init__(self, name:str, role:str, tools: List[callable]):
        self.name = name
        self.role = role
        self.tools = {tool.__name__: tool for tool in tools}

    def respond(self, message: str) -> str:
        # Create tool descriptions for the model
        tool_descriptions = []
        for tool_name, tool in self.tools.items():
            sig = inspect.signature(tool)
            properties = {}
            required = []
            
            for param_name, param in sig.parameters.items():
                properties[param_name] = {
                    "type": "string",
                    "description": f"Parameter: {param_name}"
                }
                if param.default == inspect.Parameter.empty:
                    required.append(param_name)
            
            if not properties:
                properties = {}
                required = []
            
            tool_descriptions.append({
                "type": "function",   
                "function": {
                    "name": tool_name,
                    "description": tool.__doc__ or f"Call the {tool_name} function",
                    "parameters": {
                        "type": "object",
                        "properties": properties,
                        "required": required
                    }
                }
            })

        # Call OpenAI with function calling
        response = openai.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": self.role},
                {"role": "user", "content": message}
            ],
            tools=tool_descriptions,
            tool_choice="auto"  # Let the model decide when to use tools
        )

        # Handle function calls
        if response.choices[0].message.tool_calls:
            tool_call = response.choices[0].message.tool_calls[0]
            function_name = tool_call.function.name
            arguments = json.loads(tool_call.function.arguments)

            # Execute the function
            if function_name in self.tools:
                func = self.tools[function_name]
                # Call function with appropriate arguments
                if arguments:
                    result = func(**arguments)
                else:
                    result = func()
                return f"{self.name}: {result}"

        # Regular response if no function call
        return f"{self.name}: {response.choices[0].message.content}"

### Puzzle generation and validation tools ###    
def generate_riddle() -> str:
    """Returns a riddle puzzle (question + correct answer) generated by LLM."""
    prompt = "Generate a single riddle puzzle for an escape room. Format: RIDDLE: [riddle question] ANSWER: [short answer]"
    return gpt.run(prompt)

def generate_math_puzzle() -> str:
    """Returns a math puzzle (question + correct answer) generated by LLM."""
    prompt = "Generate a single math puzzle for an escape room. Format: PUZZLE: [math question] ANSWER: [numerical answer]"
    return gpt.run(prompt)

def generate_word_puzzle() -> str:
    """Returns a word puzzle (question + correct answer) generated by LLM."""
    prompt = "Generate a single word puzzle for an escape room. Format: PUZZLE: [word puzzle question] ANSWER: [short word answer]"
    return gpt.run(prompt)

def random_puzzle(type=None):
    """Picks a puzzle type at random (or based on type) and generates via LLM."""
    if type == "riddle":
        return generate_riddle()
    elif type == "math":
        return generate_math_puzzle()
    elif type == "word":
        return generate_word_puzzle()
    else:
        puzzle_func = random.choice([generate_riddle, generate_math_puzzle, generate_word_puzzle])
        return puzzle_func()

def parse_puzzle_response(response):
    """Uses LLM to intelligently extract question and answer from puzzle response."""
    prompt = f"""You are a puzzle extractor. Given a puzzle text that contains both a question and an answer, 
extract them separately and return ONLY this format (nothing else):
QUESTION: [the puzzle question without the answer]
ANSWER: [the correct answer - just the answer value, nothing else]

Puzzle to extract from:
{response}"""
    
    result = gpt.run(prompt)
    
    # Parse the LLM's extraction
    
    question_match = re.search(r'QUESTION:\s*(.+?)(?=ANSWER:|$)', result, re.IGNORECASE | re.DOTALL)
    answer_match = re.search(r'ANSWER:\s*(.+?)$', result, re.IGNORECASE | re.DOTALL)
    
    question = question_match.group(1).strip() if question_match else response.strip()
    answer = answer_match.group(1).strip() if answer_match else ""
    
    return {"question": question, "answer": answer}

def validate_puzzle_with_llm(puzzle_question: str, puzzle_answer: str) -> dict:
    """
    Use LLM to validate that the answer actually solves the puzzle.
    Returns: {"valid": True/False, "reason": "explanation"}
    """
    prompt = f"""You are a puzzle validator. Check if the provided answer actually solves the puzzle.

PUZZLE QUESTION:
{puzzle_question}

PROVIDED ANSWER:
{puzzle_answer}

Analyze carefully:
1. Read the puzzle question thoroughly
2. Solve it yourself step-by-step
3. Check if there are multiple possible answers
4. Verify the provided answer is correct and unambiguous
5. If multiple answers are possible, the puzzle is INVALID (ambiguous)

Respond with ONLY this JSON format:
{{
    "valid": true or false,
    "reason": "brief explanation",
    "correct_answer": "the correct answer if provided one is wrong, otherwise null",
    "ambiguous": true or false,
    "alternative_answers": ["list", "of", "other", "possible", "answers"] or null
}}

CRITICAL: If a puzzle has multiple valid answers (like "joke" vs "laughter" vs "riddle"), mark it as INVALID with ambiguous=true."""

    try:
        client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"}
        )
        result = json.loads(response.choices[0].message.content)
        
        # If ambiguous, mark as invalid
        if result.get("ambiguous", False):
            result["valid"] = False
            if not result.get("reason"):
                result["reason"] = "Puzzle has multiple possible answers (ambiguous)"
        
        return result
    except Exception as e:
        return {
            "valid": False,
            "reason": f"Validation error: {e}",
            "correct_answer": None,
            "ambiguous": False
        }

### Game State Manager tools ###
game_state = {
    "solved_puzzles": [],
    "unsolved_puzzles": [],
    "attempts": {}
}

def check_player_answer(puzzle_question: str, correct_answer, player_answer) -> str:
    """Uses LLM to intelligently check if player's answer is correct, considering synonyms and variations."""
    prompt = f"""You are validating a player's answer to a puzzle.

PUZZLE QUESTION:
{puzzle_question}

CORRECT ANSWER:
{correct_answer}

PLAYER'S ANSWER:
{player_answer}

Determine if the player's answer is correct. Consider:
1. Exact matches (case-insensitive)
2. Synonyms or semantically equivalent answers
3. Minor spelling variations or typos
4. Alternative phrasings of the same answer

Examples:
- Correct: "keyboard" vs "key board" → CORRECT
- Correct: "echo" vs "an echo" → CORRECT  
- Correct: "4" vs "four" → CORRECT
- Incorrect: "joke" vs "laughter" → INCORRECT (different words)

Respond with ONLY "True" if correct or "False" if incorrect. No explanation and no additional text.
"""

    result = gpt.run(prompt)
    return result

### Hint Master Agent tools ###

# Global hint state tracking
hint_state = {
    "current_puzzle_id": None,
    "hints_given_count": 0
}

def get_hint(puzzle_question: str, puzzle_answer: str, attempt_count: str) -> str:
    """Provides a hint based on the puzzle question, answer, and number of attempts via LLM."""
    # Increment the hint counter in global state
    hint_state["hints_given_count"] += 1
    attempt_level = hint_state["hints_given_count"]
    
    # Cap at 5 levels
    attempt_level = min(attempt_level, 5)
    
    hint_instructions = {
        1: "Give a very subtle hint that guides toward the solution type. Reference something specific about the puzzle question.",
        2: "Give a hint that points toward a specific aspect of the puzzle. Use elements from the puzzle question to guide them.",
        3: "Give a more direct hint. Reference the puzzle question and guide significantly toward the answer type.",
        4: "Give a very direct hint. You can mention what category the answer falls into or give a strong clue about the answer.",
        5: "Give a hint that's almost the answer. You can reveal part of the answer or describe it very explicitly."
    }
    
    prompt = f"""You are a hint master for escape room puzzles.

PUZZLE QUESTION: {puzzle_question}
CORRECT ANSWER: {puzzle_answer}
HINT LEVEL: {attempt_level}

{hint_instructions[attempt_level]}

CRITICAL RULES:
1. Use the ACTUAL puzzle question and answer above to create your hint
2. Reference specific words or concepts from the puzzle question
3. Do NOT give generic hints like "think carefully" or "look for patterns"
4. Your hint must guide toward the specific answer: {puzzle_answer}
5. Keep it to 1-2 sentences maximum

Provide ONLY the hint text, nothing else:"""
    
    return gpt.run(prompt)

def reset_hints(puzzle_id: str = "new_puzzle"):
    """Resets hint progression for a new puzzle."""
    hint_state["current_puzzle_id"] = puzzle_id
    hint_state["hints_given_count"] = 0
    return f"Hints have been reset for puzzle: {puzzle_id}"

### Narrator Agent tools ###
def intro_story():
    """Sets the opening scene via LLM narrative."""
    prompt = f"""You are a narrator for an escape room adventure.

        First, greet the player and explain the game:
        - They need to solve {num_puzzles} puzzles to escape the ancient temple
        - They can type 'hint' to get up to 3 hints per puzzle
        - They have 5 attempts per puzzle

        Then, create an immersive opening scene (2-3 sentences) that sets the mood for the ancient temple escape room.

        Be dramatic and engaging!"""
    return gpt.run(prompt)

def narrate_success(puzzle):
    """Narrates success after solving a puzzle via LLM."""
    prompt = f"Narrate in 1-2 sentences how the player successfully solved this puzzle: {puzzle}. Use dramatic, celebratory language."
    return gpt.run(prompt)

def narrate_failure(puzzle):
    """Adds drama when the player fails to solve a puzzle via LLM."""
    prompt = f"Write 1-2 sentences of dramatic narration about the player failing to solve this puzzle: {puzzle}. The temple is trapping them."
    return gpt.run(prompt)

def ending(success=True):
    """Concludes the story based on success or failure via LLM."""
    if success:
        prompt = "Write a triumphant 2-3 sentence ending to an escape room story where the player successfully escaped the ancient temple."
    else:
        prompt = "Write a tragic 2-3 sentence ending to an escape room story where the player failed to escape the ancient temple."
    return gpt.run(prompt)

### Instantiate Agents ###

puzzle_generator_agent = Puzzle_Agent(
    name = "Puzzle_Generator",
    role = "You are responsible for generating and validating puzzles.", 
    tools=[
            generate_riddle,
            generate_math_puzzle,
            generate_word_puzzle,
            random_puzzle
])

game_state_manager_agent = Puzzle_Agent(
    name = "Game_State_Manager",
    role = "You validate player answers and determine if they are correct, considering synonyms and variations.",
    tools=[
            check_player_answer
])

hint_master_agent = Puzzle_Agent(
    name = "Hint_Master",
    role = "You provide specific, helpful hints for escape room puzzles based on the question and answer. Always reference the actual puzzle content in your hints.",
    tools=[
            get_hint,
            reset_hints
])

narrator_agent = Puzzle_Agent(
    name = "Narrator",
    role = "You are responsible for immersing the player in the escape room story and reacting to progress.",
    tools=[
            intro_story,
            narrate_success,
            narrate_failure,
            ending
])

class Orchestrator:
  
    
    def __init__(self):
        self.game_state = {
            "total_puzzles": 0,
            "current_puzzle_index": 0,
            "puzzles": [],
            "current_attempts": 0,
            "max_attempts": 5,
            "hints_given": 0,
            "max_hints": 3
        }
    
    def play_game(self, num_puzzles: int = 3):
        """Main game loop with AI decision-making."""
        print("\n" + "="*70)
        print("AI-POWERED ESCAPE ROOM")
        print("="*70 + "\n")
        
        self.game_state["total_puzzles"] = num_puzzles
        game_state["unsolved_puzzles"] = list(range(num_puzzles))
        
        # Intro - Let narrator tell the story
        response = narrator_agent.respond(
            f"Tell the opening story. The player must solve {num_puzzles} puzzles to escape."
        )
        print(response)
        input("\nPress Enter to continue...")
        
        # Generate puzzles
        print("\n[Generating Puzzles...]")
        puzzles = []
        for i in range(num_puzzles):
            max_generation_attempts = 3
            valid_puzzle = None
            
            for attempt in range(max_generation_attempts):
                # Generate puzzle
                puzzle_response = puzzle_generator_agent.respond(f"Generate a random puzzle")
                
                # Extract text after agent name
                if "Puzzle_Generator:" in puzzle_response:
                    puzzle_text = puzzle_response.split("Puzzle_Generator:")[-1].strip()
                else:
                    puzzle_text = puzzle_response
                
                # Parse the puzzle
                parsed = parse_puzzle_response(puzzle_text)
                puzzle = {
                    "question": parsed["question"],
                    "answer": parsed["answer"].lower().strip()
                }
                
                # Validate the puzzle
                validation = validate_puzzle_with_llm(puzzle["question"], puzzle["answer"])
                
                if validation["valid"]:
                    valid_puzzle = puzzle
                    break
                else:
                    reason = validation['reason']
                    if validation.get('ambiguous'):
                        alts = validation.get('alternative_answers', [])
                        
                    
                    # If validator provides correct answer and it's not ambiguous, use it
                    if validation.get("correct_answer") and validation["correct_answer"] and not validation.get("ambiguous"):
                        puzzle["answer"] = validation["correct_answer"].lower().strip()
                        valid_puzzle = puzzle
                        break
                    
                    # Otherwise try again
                    if attempt < max_generation_attempts - 1:
                        print(f"Regenerating...")
            
            # If no valid puzzle after all attempts, use fallback
            if not valid_puzzle:
                print(f"Using fallback puzzle {i+1}")
                fallback_puzzles = [
                    {
                        "question": "I speak without a mouth and hear without ears. What am I?",
                        "answer": "echo"
                    },
                    {
                        "question": "What has keys but no locks, space but no room, and you can enter but can't go inside?",
                        "answer": "keyboard"
                    },
                    {
                        "question": "I'm tall when I'm young and short when I'm old. What am I?",
                        "answer": "candle"
                    }
                ]
                valid_puzzle = fallback_puzzles[i % len(fallback_puzzles)]
            
            puzzles.append(valid_puzzle)
        
        self.game_state["puzzles"] = puzzles
        
        # Play each puzzle
        for puzzle_idx, puzzle in enumerate(puzzles):
            print(f"\n{'='*70}")
            print(f"PUZZLE {puzzle_idx + 1}/{num_puzzles}")
            print(f"{'='*70}\n")
            
            self.game_state["current_puzzle_index"] = puzzle_idx
            self.game_state["current_attempts"] = 0
            self.game_state["hints_given"] = 0
            
            # Use hint master agent to reset hints for new puzzle
            hint_master_agent.respond(f"Reset the hints for puzzle {puzzle_idx + 1}")
            
            puzzle_solved = False
            
            while self.game_state["current_attempts"] < self.game_state["max_attempts"] and not puzzle_solved:
                # Display puzzle
                print(f"❓ {puzzle['question']}\n")
                
                # Get player input
                user_input = input(f"🔓 Your answer (Attempt {self.game_state['current_attempts'] + 1}/{self.game_state['max_attempts']}): ").strip()
                
                if user_input.lower() == "quit":
                    print("\nThanks for playing!")
                    return
                
                # Handle hint request
                if user_input.lower() == "hint":
                    if self.game_state["hints_given"] < self.game_state["max_hints"]:
                        self.game_state["hints_given"] += 1
                        
                        # Let hint master provide the hint (no attempt_count needed - uses global state)
                        hint_request = f"""Provide a hint for the following puzzle:

Puzzle Question: {puzzle['question']}
Puzzle Answer: {puzzle['answer']}
Attempt Number: {self.game_state['current_attempts']}"""

                        response = hint_master_agent.respond(hint_request)
                        print(f"\n💡 {response}\n")
                    else:
                        print("❌ No more hints available!\n")
                    continue
                
                # Let AI validate the answer
                self.game_state["current_attempts"] += 1
                
                # Ask game state manager to validate
                validation_request = f"""Check if the player's answer is correct.

Puzzle Question: {puzzle['question']}
Correct Answer: {puzzle['answer']}
Player's Answer: {user_input}
Current Attempts: {self.game_state['current_attempts']}/{self.game_state['max_attempts']}
"""

                response = game_state_manager_agent.respond(validation_request)
                response = response.lower()
                
                if "true" in response:
                    puzzle_solved = True
                    game_state["solved_puzzles"].append(puzzle_idx)
                    if puzzle_idx in game_state["unsolved_puzzles"]:
                        game_state["unsolved_puzzles"].remove(puzzle_idx)
                    
                    # Let narrator celebrate
                    celebration = narrator_agent.respond(
                        f"The player solved the puzzle! Celebrate their success."
                    )
                    print(f"\n{celebration}\n")
                    
                elif self.game_state["current_attempts"] >= self.game_state["max_attempts"]:
                    # Max attempts reached - game over
                    failure = narrator_agent.respond(
                        f"The player failed after {self.game_state['max_attempts']} attempts. The correct answer was '{puzzle['answer']}'. Dramatize their failure and end the game."
                    )
                    print(f"\n{failure}\n")
                    return
                    
                else:
                    # Still have attempts left
                    remaining = self.game_state["max_attempts"] - self.game_state["current_attempts"]
                    print(f"❌ Incorrect. {remaining} attempts remaining.\n")
            
            if puzzle_idx < len(puzzles) - 1 and puzzle_solved:
                input("\nPress Enter for the next puzzle...")
        
        # Victory!
        response = narrator_agent.respond("Write a triumphant ending - the player escaped!")
        print(f"\n{response}\n")
        
        print("\n" + "="*70)
        print("🎉 CONGRATULATIONS! YOU ESCAPED! 🎉")
        print("="*70 + "\n")


if __name__ == "__main__":
    orchestrator = Orchestrator()
    num_puzzles = input("Enter number of puzzles to solve (default 2): ")
    if not num_puzzles.isdigit():
        num_puzzles = 2
    else:
        num_puzzles = int(num_puzzles)
    orchestrator.play_game(num_puzzles)